const assert=require('node:assert/strict'),C=require('../assets/core.js');
let count=0;function test(name,fn){fn();console.log('PASS '+name);count++;}
const line={description:'Test',quantity:2,rate:100,discountPct:10,gstRate:18};
test('intra-state GST and discount',()=>{let t=C.totals([line],false,'GST');assert.equal(t.taxableValue,180);assert.equal(t.cgst,16.2);assert.equal(t.sgst,16.2);assert.equal(t.igst,0);assert.equal(t.grandTotal,212);assert.equal(t.roundOff,-.4);});
test('inter-state IGST',()=>{let t=C.totals([line],true,'GST');assert.equal(t.igst,32.4);assert.equal(t.cgst,0);});
test('Bill of Supply has no tax',()=>assert.equal(C.totals([line],false,'BOS').grandTotal,180));
test('invalid and empty inputs rejected',()=>{for(let value of [-1,NaN,Infinity])assert.throws(()=>C.totals([{...line,rate:value}],false,'GST'));assert.throws(()=>C.totals([{...line,quantity:0}],false,'GST'));assert.throws(()=>C.totals([{...line,discountPct:101}],false,'GST'));assert.throws(()=>C.totals([],false,'BOS'));});
function fixture(){let d=C.initial();d.customers.push({id:'c',name:'Buyer',state:'West Bengal'});d.items.push({id:'p',name:'Product',stockQty:5,salePrice:100,gstRate:0});return d;}
const input={customerId:'c',type:'BOS',date:C.date(),lines:[{...line,itemId:'p'}]};
test('stock, numbering and historical snapshots',()=>{let d=fixture(),i=C.create(d,input);assert.equal(d.items[0].stockQty,3);assert.equal(i.number,'BILL-0001');d.customers[0].name='Changed';d.business.name='Changed';assert.equal(i.customer.name,'Buyer');assert.equal(i.business.name,'Suman Murmu');assert.equal(C.create(d,input).number,'BILL-0002');});
test('aggregate stock checks are atomic',()=>{let d=fixture();assert.throws(()=>C.create(d,{...input,lines:[{...line,itemId:'p',quantity:3},{...line,itemId:'p',quantity:3}]}));assert.equal(d.items[0].stockQty,5);assert.equal(d.invoices.length,0);assert.equal(d.business.seq,1);});
test('partial and full payments; overpayment rejected',()=>{let d=fixture(),i=C.create(d,input);C.payment(i,50,'UPI');assert.equal(C.status(i),'PARTIALLY_PAID');assert.throws(()=>C.payment(i,1000));C.payment(i,130);assert.equal(C.status(i),'PAID');assert.throws(()=>C.payment(i,0));assert.equal(i.payments.length,2);});
test('cancellation restores stock exactly once',()=>{let d=fixture(),i=C.create(d,input);C.cancel(d,i);C.cancel(d,i);assert.equal(d.items[0].stockQty,5);assert.equal(C.status(i),'CANCELLED');assert.throws(()=>C.payment(i,1));});
test('paid bills cannot be cancelled',()=>{let d=fixture(),i=C.create(d,{...input,paid:50});assert.throws(()=>C.cancel(d,i));assert.equal(d.items[0].stockQty,3);});
test('GST requires registration',()=>assert.throws(()=>C.create(fixture(),{...input,type:'GST'})));
test('backup validation and round-trip',()=>{let d=fixture();C.create(d,input);assert.deepEqual(C.validate(JSON.parse(JSON.stringify(d))),d);assert.throws(()=>C.validate({version:1}));let invalid=fixture();invalid.items[0].stockQty=-1;assert.throws(()=>C.validate(invalid));});
test('fractional stock precision and aggregate floating point',()=>{let d=fixture();d.items[0].stockQty=.3;let i=C.create(d,{...input,lines:[{...line,itemId:'p',quantity:.1},{...line,itemId:'p',quantity:.2}]});assert.equal(d.items[0].stockQty,0);C.cancel(d,i);assert.equal(d.items[0].stockQty,.3);});
test('QR sizing preserves aspect ratio and handles large originals',()=>{assert.deepEqual(C.qrSize(2400,1200),{width:180,height:90});assert.deepEqual(C.qrSize(1200,2400),{width:90,height:180});assert.deepEqual(C.qrSize(100,100),{width:100,height:100});assert.throws(()=>C.qrSize(0,1));});
test('bank details preserve leading zeros and validate IFSC',()=>{const b={bankName:'Bank',accountHolder:'Owner',bankAccount:'001234567890',bankIfsc:'SBIN0001234'};C.checkBank(b);assert.equal(b.bankAccount,'001234567890');assert.throws(()=>C.checkBank({...b,bankIfsc:'INVALID'}));assert.throws(()=>C.checkBank({...b,accountHolder:''}));assert.throws(()=>C.checkBank({...b,bankAccount:'<script>'}));});
test('version 1 data migrates without changing bills or image bytes',()=>{const d=fixture(),i=C.create(d,input);for(let key of ['bankName','accountHolder','bankAccount','bankIfsc','bankBranch','supportEmail','qrSizing']){delete d.business[key];delete i.business[key];}const before=JSON.stringify(i.items);C.migrate(d);assert.equal(d.business.bankName,'');assert.equal(i.business.bankAccount,'');assert.equal(JSON.stringify(i.items),before);assert.equal(d.invoices.length,1);});
test('support email validation rejects invalid addresses',()=>{C.checkSupport({supportEmail:'help@example.test'});C.checkSupport({supportEmail:''});assert.throws(()=>C.checkSupport({supportEmail:'bad\n@example.test'}));});
console.log(`${count} tests passed`);
