const {JSDOM}=require('jsdom'),{indexedDB}=require('fake-indexeddb'),fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const assets=path.join(__dirname,'../assets'),errors=[];
function setup(){let dom=new JSDOM(fs.readFileSync(path.join(assets,'index.html'),'utf8').replace(/<script[^>]*><\/script>/g,''),{url:'https://app.billbook.local/',runScripts:'dangerously'}),w=dom.window;w.indexedDB=indexedDB;w.confirm=()=>true;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.addEventListener('error',e=>errors.push(e.message));for(let file of ['core.js','app.js']){let s=w.document.createElement('script');s.textContent=fs.readFileSync(path.join(assets,file),'utf8');w.document.body.appendChild(s);}return w;}
const delay=()=>new Promise(r=>setTimeout(r,30));
(async()=>{let w=setup();await delay();let $=id=>w.document.getElementById(id),get=s=>w.eval(s),fill=(id,v)=>{$(id).value=v;$(id).dispatchEvent(new w.Event('input'));};
assert(get('loaded'));w.navigate('customers');w.editRecord('customers','');fill('name','Buyer <b>');fill('phone','9999999999');await w.saveRecord(new w.Event('submit'),'customers','');assert.equal(get('db.customers[0].name'),'Buyer <b>');assert(!w.document.querySelector('h3 b'));
w.navigate('items');w.editRecord('items','');fill('name','Notebook');fill('price','100');fill('stock','10');fill('gst','18');await w.saveRecord(new w.Event('submit'),'items','');
w.navigate('new');$('product0').value=get('db.items[0].id');w.pickProduct(0);fill('qty0','2');fill('discount0','10');fill('paid','50');await w.saveInvoice(new w.Event('submit'));assert.equal(get('currentInvoice().grandTotal'),180);assert.equal(get('db.items[0].stockQty'),8);fill('payamount','130');await w.recordPayment(new w.Event('submit'));assert.equal(get('C.status(currentInvoice())'),'PAID');
w.close();w=setup();await delay();$=id=>w.document.getElementById(id);get=s=>w.eval(s);fill=(id,v)=>{$(id).value=v;$(id).dispatchEvent(new w.Event('input'));};assert.equal(get('db.invoices.length'),1);assert.equal(get('db.invoices[0].amountPaid'),180);
w.navigate('settings');fill('bgstin','19ABCDE1234F1Z5');fill('bankname','State Bank <India>');fill('holder','Suman Murmu');fill('account','001234567890');fill('ifsc','sbin0001234');fill('branch','Kolkata');fill('supportemail','help@example.test');await w.saveSettings(new w.Event('submit'));
const buf=fs.readFileSync(path.join(__dirname,'../res/drawable/icon.png'));w.Image=class{constructor(){this.naturalWidth=2400;this.naturalHeight=1200;}set src(s){this.data=s;setTimeout(()=>this.onload(),0);}};
await w.uploadQR({target:{files:[new w.File([buf],'test.png',{type:'image/png'})]}});assert.equal(get('db.business.qr.split(",")[1]'),buf.toString('base64'));assert.equal(get('db.business.qrWidth'),2400);
w.navigate('new');$('doctype').value='GST';$('product0').value=get('db.items[0].id');w.pickProduct(0);await w.saveInvoice(new w.Event('submit'));assert.equal(get('currentInvoice().grandTotal'),118);let html=get('invoiceHtml(currentInvoice())');assert(html.includes('Buyer &lt;b&gt;'));assert(html.includes('width="180" height="90"'));assert(html.includes(buf.toString('base64')));assert(html.includes('State Bank &lt;India&gt;'));assert(html.includes('001234567890'));assert(html.includes('SBIN0001234'));assert.equal(get('db.invoices[0].business.bankIfsc'),'SBIN0001234');assert.equal(get('db.invoices[1].business.bankAccount'),'');assert($('app').textContent.includes('Copy payment details'));
let copied,request;w.Android={copyText:t=>copied=t,contactSupport:(email,subject,body)=>request={email,subject,body}};w.copyPaymentDetails();assert(copied.includes('001234567890'));w.navigate('support');fill('supportissue','Print button does not respond');w.contactSupport();assert.equal(request.email,'help@example.test');assert(request.body.includes('Print button does not respond'));assert(!request.body.includes('001234567890'));assert(!request.body.includes(buf.toString('base64')));w.visualViewport={height:800};w.updateKeyboardLayout();$('supportissue').focus();w.visualViewport.height=400;w.updateKeyboardLayout();assert(w.document.body.classList.contains('keyboard-open'));w.visualViewport.height=800;w.updateKeyboardLayout();assert(!w.document.body.classList.contains('keyboard-open'));w.navigate('settings');fill('account','999999999999');await w.saveSettings(new w.Event('submit'));assert.equal(get('db.invoices[0].business.bankAccount'),'001234567890');w.navigate('detail',get('db.invoices[0].id'));assert(get('invoiceHtml(currentInvoice())').includes('001234567890'));html=get('invoiceHtml(currentInvoice())');
let pdfJob,pickCount=0;w.Android={sharePdf:(json,name)=>{pdfJob={data:JSON.parse(json),name}},pickContact:()=>pickCount++};w.shareInvoicePdf();assert.equal(pdfJob.name,'BILL-0002');assert.equal(pdfJob.data.grandTotal,118);assert.equal(pdfJob.data.business.bankAccount,'001234567890');assert.equal(pdfJob.data.pdfStatus,'UNPAID');assert($('sharepdf').disabled);w.onPdfShareDone(true);assert(!$('sharepdf').disabled);w.navigate('customers');const beforeContacts=get('db.customers.length');w.addCustomerFromContacts();assert.equal(pickCount,1);w.receiveContact({name:'Imported <Contact>',phone:'+91 99999 99999'});assert.equal($('name').value,'Imported <Contact>');assert.equal($('phone').value,'+91 99999 99999');assert.equal($('state').value,'West Bengal');assert.equal(get('db.customers.length'),beforeContacts);assert($('toast').textContent.includes('already exists'));fill('phone','8888888888');await w.saveRecord(new w.Event('submit'),'customers','');assert.equal(get('db.customers.length'),beforeContacts+1);assert.equal(get('db.customers[1].name'),'Imported <Contact>');w.navigate('detail',get('db.invoices[0].id'));
let printJob;w.Android={printInvoice:(html,name)=>{printJob={html,name}},shareText:()=>{},exportBackup:()=>{}};w.printBill();assert.equal(printJob.name,'BILL-0002');assert.equal(printJob.html,html);
await w.cancelInvoice();assert.equal(get('db.items[0].stockQty'),8);assert.equal(get('C.status(currentInvoice())'),'CANCELLED');w.navigate('reports');assert.equal(get('stats().sales'),180);assert($('report').textContent.includes('₹180.00'));
let backup=get('JSON.stringify(db)');await w.restoreBackup(backup);assert.equal(get('db.invoices.length'),2);await w.restoreBackup('{"version":1}');assert.equal(get('db.invoices.length'),2);assert($('toast').textContent.includes('Restore failed'));
assert.deepEqual(errors,[]);w.close();console.log('PASS DOM integration: customer/product forms, bill creation, payments, persistence across restart, GST, QR byte identity and adaptive sizing, bank snapshots and email draft privacy, escaped invoice HTML, Android print/PDF-share bridges, contact picker/review/save, cancellation, reports and backup restore.');})().catch(e=>{console.error(e);process.exitCode=1});
