const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const fs=require('fs'),http=require('http');const root=path.resolve(__dirname,'../assets');const server=http.createServer((req,res)=>{const file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(8088,'127.0.0.1',r));const b=await chromium.launch({executablePath:process.env.BILLBOOK_CHROME,args:['--no-sandbox','--no-process-singleton','--no-zygote','--single-process']});const context=await b.newContext({viewport:{width:393,height:852}});const p=await context.newPage();let errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.goto('http://localhost:8088');await p.getByText('Business made simple.').waitFor();
await p.getByRole('button',{name:'Customers',exact:true}).click();await p.getByRole('button',{name:'+ Add customer',exact:true}).click();await p.locator('#name').fill('Test Buyer <b>');await p.locator('#phone').fill('9999999999');await p.getByRole('button',{name:'Save',exact:true}).click();await p.getByText('Test Buyer <b>',{exact:true}).waitFor();
await p.getByRole('button',{name:'Products',exact:true}).click();await p.getByRole('button',{name:'+ Add product',exact:true}).click();await p.locator('#name').fill('Notebook');await p.locator('#price').fill('100');await p.locator('#stock').fill('10');await p.locator('#gst').fill('18');await p.getByRole('button',{name:'Save',exact:true}).click();await p.getByText('Notebook',{exact:true}).waitFor();
await p.getByRole('button',{name:'Home',exact:true}).click();await p.getByRole('button',{name:'+ Create a bill'}).click();await p.locator('#product0').selectOption({label:'Notebook · 10 pcs'});await p.locator('#qty0').fill('2');await p.locator('#discount0').fill('10');await p.locator('#paid').fill('50');await p.getByRole('button',{name:'Save bill',exact:true}).click();await p.getByRole('heading',{name:'BILL-0001',exact:true}).waitFor();assert.equal(await p.evaluate(()=>currentInvoice().grandTotal),180);assert.equal(await p.evaluate(()=>db.items[0].stockQty),8);await p.locator('#payamount').fill('130');await p.getByRole('button',{name:'Record payment',exact:true}).click();await p.getByText('PAID',{exact:true}).waitFor();await p.evaluate(()=>{window.Android={sharePdf:(json,name)=>{window.pdfRequest={data:JSON.parse(json),name};onPdfShareDone(true)}}});await p.getByRole('button',{name:'Share PDF',exact:true}).click();assert.equal(await p.evaluate(()=>pdfRequest.data.pdfStatus),'PAID');assert.equal(await p.evaluate(()=>pdfRequest.name),'BILL-0001');
await p.reload();await p.getByText('Business made simple.').waitFor();assert.equal(await p.evaluate(()=>db.invoices.length),1);assert.equal(await p.evaluate(()=>db.invoices[0].amountPaid),180);
await p.getByRole('button',{name:'Settings',exact:true}).click();await p.locator('#bgstin').fill('19ABCDE1234F1Z5');await p.locator('#bankname').fill('State Bank of India');await p.locator('#holder').fill('Suman Murmu');await p.locator('#account').fill('001234567890');await p.locator('#ifsc').fill('SBIN0001234');await p.locator('#supportemail').fill('help@example.test');await p.getByRole('button',{name:'Save business details',exact:true}).click();await p.getByText('Business details saved.',{exact:true}).waitFor();
const fixture=path.resolve(__dirname,'../res/drawable/icon.png');await p.locator('#qrfile').setInputFiles(fixture);await p.getByText('QR saved. It will automatically fit screens and PDFs.',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>db.business.qr.split(',')[1]),fs.readFileSync(fixture).toString('base64'));
await p.getByRole('button',{name:'Home',exact:true}).click();await p.getByRole('button',{name:'+ Create a bill'}).click();await p.locator('#doctype').selectOption('GST');await p.locator('#product0').selectOption({label:'Notebook · 8 pcs'});await p.getByRole('button',{name:'Save bill',exact:true}).click();await p.getByRole('heading',{name:'BILL-0002',exact:true}).waitFor();assert.equal(await p.evaluate(()=>currentInvoice().grandTotal),118);let html=await p.evaluate(()=>invoiceHtml(currentInvoice()));assert(html.includes('Test Buyer &lt;b&gt;'));assert(!html.includes('001234567890'));assert(html.includes('width="144" height="144"'));let print=await p.context().newPage();await print.setContent(html);await print.pdf({path:path.resolve(__dirname,'../../../BillBook-sample.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true});
// Exercise bill edits through the visible form, then restore the original quantity.
await p.getByRole('button',{name:'Edit bill',exact:true}).click();await p.locator('#qty0').fill('2');await p.locator('#notes').fill('Modified bill');await p.getByRole('button',{name:'Save changes',exact:true}).click();await p.getByRole('heading',{name:'BILL-0002',exact:true}).waitFor();assert.equal(await p.evaluate(()=>currentInvoice().grandTotal),236);assert.equal(await p.evaluate(()=>db.items[0].stockQty),6);assert.equal(await p.evaluate(()=>db.business.seq),3);
await p.getByRole('button',{name:'Edit bill',exact:true}).click();await p.locator('#qty0').fill('1');await p.getByRole('button',{name:'Save changes',exact:true}).click();await p.getByRole('heading',{name:'BILL-0002',exact:true}).waitFor();assert.equal(await p.evaluate(()=>db.items[0].stockQty),7);
await p.getByRole('button',{name:'Cancel bill & restore stock',exact:true}).click();await p.getByText('CANCELLED',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>db.items[0].stockQty),8);
await p.getByRole('button',{name:'Reports',exact:true}).click();await p.getByRole('heading',{name:'Reports',exact:true}).waitFor();assert.equal(await p.evaluate(()=>stats().sales),180);
await p.getByRole('button',{name:'Home',exact:true}).click();await p.screenshot({path:path.resolve(__dirname,'../../../BillBook-preview.png'),fullPage:true});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const size of [{width:280,height:700},{width:320,height:700},{width:393,height:852},{width:780,height:460},{width:1024,height:768},{width:1440,height:900}]){await p.setViewportSize(size);for(const screen of ['home','settings','bills','customers','items','reports','support','detail','new']){await p.evaluate(({screen})=>{draft=null;navigate(screen,db.invoices[0].id);},{screen});if(!await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)){console.log(await p.evaluate(()=>[...document.querySelectorAll('*')].filter(e=>e.getBoundingClientRect().right>innerWidth).map(e=>({tag:e.tagName,cls:e.className,text:e.textContent.slice(0,80),width:e.getBoundingClientRect().width})).slice(-12)));await p.screenshot({path:'/tmp/bill-overflow.png'});throw Error('Overflow '+screen+' at '+size.width);}if(screen==='settings'){const qr=await p.locator('.qrbox img').boundingBox();assert(qr.width<=240&&qr.height<=240);}}await p.evaluate(()=>{draft=null;navigate('home')});await p.screenshot({path:path.resolve(__dirname,'../../../qa/preview-'+size.width+'.png'),fullPage:true});}await p.evaluate(()=>{navigate('customers');window.Android={pickContact:()=>receiveContact({name:'Phone Contact',phone:'9876543210'})};});await p.getByRole('button',{name:'Add from contacts',exact:true}).click();assert.equal(await p.locator('#name').inputValue(),'Phone Contact');assert.equal(await p.locator('#phone').inputValue(),'9876543210');assert.equal(await p.evaluate(()=>db.customers.length),1);await p.getByRole('button',{name:'Save',exact:true}).click();await p.getByText('Phone Contact',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>db.customers.length),2);for(const width of [280,393,1024]){await p.setViewportSize({width,height:852});await p.evaluate(()=>navigate('support'));await p.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));assert(await p.evaluate(()=>{const nav=document.getElementById('nav'),main=document.getElementById('app');return innerWidth>=900||parseFloat(getComputedStyle(main).paddingBottom)>nav.getBoundingClientRect().height&&main.lastElementChild.getBoundingClientRect().bottom<=nav.getBoundingClientRect().top;}));}// Bank visibility changes only after a recorded transfer, across all output paths.
await p.evaluate(async()=>{const i=await mutate(d=>C.create(d,{customerId:d.customers[0].id,type:'BOS',date:C.date(),lines:[{description:'Service',quantity:1,rate:100,discountPct:0,gstRate:0}],paid:0,mode:'Bank transfer'}));navigate('detail',i.id);});
assert(!(await p.locator('#app').innerText()).includes('001234567890'));await p.locator('#payamount').fill('10');await p.locator('#paymode').selectOption('Bank transfer');await p.getByRole('button',{name:'Record payment',exact:true}).click();await p.getByText('PARTIALLY PAID',{exact:true}).waitFor();assert((await p.locator('#app').innerText()).includes('001234567890'));assert(await p.evaluate(()=>invoiceHtml(currentInvoice()).includes('001234567890')));
await p.getByRole('button',{name:'Edit bill',exact:true}).click();assert(await p.locator('#paid').isDisabled());await p.locator('#rate0').fill('5');await p.getByRole('button',{name:'Save changes',exact:true}).click();await p.getByText('Bill total cannot be less than recorded payments.',{exact:true}).waitFor();await p.locator('#rate0').fill('120');await p.getByRole('button',{name:'Save changes',exact:true}).click();await p.getByRole('heading',{name:'BILL-0003',exact:true}).waitFor();assert.equal(await p.evaluate(()=>currentInvoice().amountPaid),10);
await p.getByRole('button',{name:'Delete bill',exact:true}).click();await p.getByRole('heading',{name:'Bills',exact:true}).waitFor();assert.equal(await p.evaluate(()=>db.invoices.length),2);assert.equal(await p.evaluate(()=>stats().sales),180);
assert.deepEqual(errors,[]);console.log('PASS UI: customer/product CRUD, bill creation, payment, reload persistence, GST, QR byte identity, HTML escaping, PDF, cancellation, stock, reports and contact import review/save, PDF-share payload, and navigation spacing across six screen sizes.');await b.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
